Cirykpopeye\GoogleBusinessClient\Entity\Review:
  type: mappedSuperclass
  table: google_reviews
  repositoryClass: Cirykpopeye\GoogleBusinessClient\Repository\ReviewRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    locale:
      type: string
    comment:
      type: text
    starRating:
      type: string
    createdOn:
      type: datetime
    reviewId:
      type: string
    reviewer:
      type: string
    profilePhoto:
      type: string
    updatedAt:
      type: datetime
  manyToOne:
    location:
      targetEntity: Cirykpopeye\GoogleBusinessClient\Interfaces\LocationInterface
