doctrine:
  orm:
    resolve_target_entities:
      Comsa\GoogleBusinessClient\Interfaces\LocationInterface: Comsa\GoogleBusinessClient\Entity\Location
      Comsa\GoogleBusinessClient\Interfaces\AccountInterface: Comsa\GoogleBusinessClient\Entity\Account
      Comsa\GoogleBusinessClient\Interfaces\LocationPeriodInterface: Comsa\GoogleBusinessClient\Entity\LocationPeriod
      Comsa\GoogleBusinessClient\Interfaces\ReviewInterface: Comsa\GoogleBusinessClient\Entity\Review

