services:
  Comsa\GoogleBusinessClient\Manager\Connection:
    class: Comsa\GoogleBusinessClient\Manager\Connection

  Comsa\GoogleBusinessClient\Controller\ConnectionController:
    class: Comsa\GoogleBusinessClient\Controller\ConnectionController
    arguments:
      - '@Comsa\GoogleBusinessClient\Manager\Connection'
      - '@doctrine.orm.entity_manager'
      - '@request_stack'
